require('dotenv').config();
require('./config/database'); // Make sure this is configured properly

const Product = require('./models/product');

(async function () {

  await Product.deleteMany({});
  const products = await Product.create([
    { name: 'Burton Free Thinker', brand: 'Burton',cat: 'Snowboard', brand: 'Burton', price: 349.99, description: 'Experience the thrill of carving through fresh powder with the Burton Free Thinker snowboard. This high-performance board offers unrivaled control and precision, making it the top choice for both beginners and seasoned riders. Elevate your snowboarding game with confidence and style.', img: 'https://i.imgur.com/rKHtKD8.png' },
    { name: 'Nitro Slash', brand: 'Nitro', cat: 'Snowboard', price: 449.99, description: 'Feel the rush of the mountains with the Nitro Slash snowboard. Designed for adventure seekers, this board delivers heart-pounding experiences with superior control. Unleash your inner snowboarder and conquer the slopes.', img: 'https://i.imgur.com/kAV9cA6.png' },
    { name: 'Jones Dream Weaver',brand: 'Jones', cat: 'Snowboard', price: 499.95, description: 'Embark on a whimsical journey with the Jones Dream Weaver snowboard. This board is your ticket to a surreal snowboarding adventure, crafted to bring your mountain fantasies to life. Dive into the dreamy slopes in style.', img: 'https://i.imgur.com/ZxssV8t.png' },
    { name: 'Salomon Super 8 Pro Snowboard', brand: 'Salomon',cat: 'Snowboard', price: 399.95, description: 'Experience top-tier snowboarding with the Salomon Super 8 Pro snowboard. Engineered for excellence, this board is a game-changer for riders seeking precision, power, and a touch of luxury on the slopes. Elevate your snowboarding experience.', img: 'https://i.imgur.com/HiRU9O4.png' },
    { name: 'Ride Warpig 2023',brand: 'Ride', cat: 'Snowboard', price: 379.99, description: 'Dominate the snow-covered realm with the Ride Warpig 2023 snowboard. Its cutting-edge design and performance capabilities make it the ultimate choice for shredding through the mountains with power, style, and a dose of adventure.', img: 'https://i.imgur.com/CLOahON.png' },
    { name: 'Arbor Spruce Bindings', brand: 'Arbor', cat: 'Bindings', price: 99.99, description: 'Secure your journey with the Arbor Spruce Bindings. These reliable bindings offer a perfect fit for your snowboard, enhancing your maneuverability and stability. Say goodbye to worries about precision and control on the slopes.', img: 'https://i.imgur.com/j6rHEEU.png' },
    { name: 'Women\'s Arbor Acacia Bindings', brand: 'Arbor', cat: 'Bindings', price: 93.96, description: 'Elevate your snowboarding game with the Women\'s Arbor Acacia Bindings. Designed for comfort and performance, these bindings ensure a snug and stylish fit for female riders. Experience snowboarding like never before.', img: 'https://i.imgur.com/qsiLsyo.png' },
    { name: 'Burton HitchHiker Splitboard Bindings',brand: 'Burton', cat: 'Bindings', price: 82.79, description: 'Secure your journey with the Burton HitchHiker Splitboard Bindings. These reliable bindings are crafted with durability and comfort in mind, ensuring a snug fit and maximum maneuverability. Experience adventure without boundaries.', img: 'https://i.imgur.com/ffo7pcu.png' },
    { name: 'Rossignol Rookie Snowboard Bindings', brand: 'Rossignol',cat: 'Bindings', price: 87.99, description: 'Enjoy a seamless snowboarding experience with the Rossignol Rookie Snowboard Bindings. Crafted for comfort and control, these bindings will have you gliding down the slopes with confidence and ease. Make every ride count.', img: 'https://i.imgur.com/aaaTx37.png' },
    { name: 'Rossignol Battle Snowboard Bindings', brand: 'Rossignol', cat: 'Bindings', price: 99.95, description: 'Conquer the mountains with the Rossignol Battle Snowboard Bindings. These reliable bindings offer enhanced control and precision, making them the perfect choice for passionate riders. Get ready to ride with power and style.', img: 'https://i.imgur.com/j0JKm2H.png' },
    { name: 'Union Flie Pro Snowboard Bindings', brand: 'Union', cat: 'Bindings', price: 179.95, description: 'Secure your adventure with the Union Flie Pro Snowboard Bindings. Crafted for stability and style, these bindings provide the ultimate connection to your snowboard. Get ready for thrilling descents down the slopes.', img: 'https://i.imgur.com/J2QNZ1z.png' },
    { name: 'ThirtyTwo Light JP Snowboard Boots', brand: 'Thiry-Two', cat: 'Boots', price: 187.49, description: 'Step into ultimate comfort and warmth with the ThirtyTwo Light JP Snowboard Boots. Designed for passionate riders, these boots offer a cozy fit and excellent support. Conquer the snow-covered landscape in style.', img: 'https://i.imgur.com/iBBuXwT.png' },
    { name: 'Burton Men\'s Snowboard Boots BOA',brand: 'Burton', cat: 'Boots', price: 649.95, description: 'Elevate your snowboarding experience with the Burton Men\'s Snowboard Boots BOA. Designed for superior warmth and support, these boots keep your feet cozy on the chilliest of mountain adventures. Ride with confidence and style.', img: 'https://i.imgur.com/JCA7hpd.png' },
    { name: 'Nitro Incline TLS', brand: 'Nitro', cat: 'Boots',  price: 379.90, description: 'Experience snowboarding like never before with the Nitro Incline TLS Boots. Designed for exceptional comfort and warmth, these boots offer fantastic support on the slopes. Every ride is a remarkable adventure.', img: 'https://i.imgur.com/EupCOgI.png' },
    { name: 'Salomon Faction BOA', brand: 'Salomon', cat: 'Boots', price: 167.95, description: 'Step into the world of snowboarding with the Salomon Faction BOA Boots. Designed for both beginners and experienced riders, these boots offer a snug and stylish fit. It\'s time to create memories on the mountains.', img: 'https://i.imgur.com/dAmGjGl.png' },
    { name: 'Vans Hi Standard OG Snowboard Boots 8',brand: 'Vans',  cat: 'Boots', price: 159.99, description: 'Elevate your snowboarding game with the Vans Hi Standard OG Snowboard Boots 8. Designed for superior warmth and support, these boots provide maximum maneuverability on the slopes. Conquer the snow-covered terrain in style.', img: 'https://i.imgur.com/m1qPnzz.png' },
    { name: 'Oakley Flight Deck', brand: 'Oakley', cat: 'Goggles', price: 107.99, description: 'Elevate your vision on the mountain with the Oakley Flight Deck Goggles. Offering crystal-clear clarity and protection, these goggles shield your eyes from harsh elements and UV rays. Experience the world of snowboarding with heightened visibility.', img: 'https://i.imgur.com/Eoz6ipp.png' },
    { name: 'Smith Frontier', brand: 'Smith', cat: 'Goggles', price: 40, description: 'Enhance your snowboarding experience with the Smith Frontier Goggles. Designed for clarity and protection, these goggles ensure your eyes stay shielded from harsh elements and UV rays. Enjoy snow-covered landscapes like never before.', img: 'https://i.imgur.com/pbyTySF.png' },
    { name: 'Dragon PXV Low Bridge Fit', brand: 'Dragon', cat: 'Goggles', price: 119.99, description: 'Experience the snow like never before with the Dragon PXV Low Bridge Fit Goggles. These high-quality goggles offer superior clarity and protection, ensuring your vision remains pristine on the slopes. Embrace the beauty of snow-covered landscapes.', img: 'https://i.imgur.com/uxHeren.png' },
    { name: 'Salomon LoFi Sigma Goggles', brand: 'Salomon', cat: 'Goggles', price: 56.49, description: 'Enjoy your snowboarding adventure with the Salomon LoFi Sigma Goggles. These goggles provide superior clarity and protection, keeping your eyes safe from harsh elements and UV rays. Discover the magic of snow-covered vistas.', img: 'https://i.imgur.com/7Pg38FX.png' },
    { name: 'Burton Men\'s GORE-TEX Gloves', brand: 'Burton', cat: 'Gloves', price: 159.95, description: "Protect your hands from the cold with Burton Men's GORE-TEX Gloves. Crafted for cold weather conditions, these gloves offer exceptional insulation and dexterity. Whether you're gripping your snowboard or building a snowman, your hands will stay cozy and nimble.", img: 'https://i.imgur.com/sLJ18sJ.png'},
    { name: 'Burton Men\'s GORE-TEX Mittens', brand: 'Burton', cat: 'Gloves', price: 179.95, description: "Stay warm and protected with Burton Men's GORE-TEX Mittens. Designed for cold weather conditions, these mittens offer unbeatable insulation and dexterity. Whether you're gripping your snowboard or building a snowman, your hands will stay cozy and ready for action.", img: 'https://i.imgur.com/G3nnC1V.png' },
    { name: 'North Face Men\'s Montant Ski Mitts', brand: 'North Face' , cat: 'Gloves', price: 65, description: "Defend your hands against the cold with North Face Men's Montant Ski Mitts. Designed for harsh weather, these mittens provide top-notch insulation and dexterity. Whether you're gripping your snowboard or sculpting a snowman, your hands will remain warm and nimble.", img: 'https://i.imgur.com/gkgxxuD.png' },
    { name: 'Dakine Crossfire Gloves', brand: 'Dakine', cat: 'Gloves', price: 89.95, description: "Conquer the cold with Dakine Crossfire Gloves. Engineered for chilly conditions, these gloves offer outstanding insulation and dexterity. Whether you're gripping your snowboard or shaping the perfect snowball, your hands will be warm and agile.", img: 'https://i.imgur.com/TfYiXBR.png' },
    { name: 'Giro Ldge MIPS Helmet 2024',brand: 'Giro',  cat: 'Helmet', price: 104.95, description: 'Prioritize safety with the Giro Ldge MIPS Helmet 2024. This reliable helmet is essential for every snowboarding enthusiast, featuring advanced protection technology and a comfortable fit. Keep your head secure as you master the slopes.', img: 'https://i.imgur.com/Q1rPAma.png' },
    { name: 'POC Fornix Mips Helment', brand:'POC',  cat: 'Helmet', price: 100, description: 'Guard your noggin with the POC Fornix MIPS Helmet. An essential choice for any snowboarding enthusiast, this helmet features advanced protection technology and a comfortable fit. Keep your head safe and stylish as you conquer the mountains.', img: 'https://i.imgur.com/gRiuSis.png' },
    { name: 'Anon Raider 3', brand: 'Anon',  cat: 'Helmet', price: 99.99, description: 'Prioritize safety with the Anon Raider 3 Helmet. Designed for the adventurous, this helmet features advanced protection technology and a comfortable fit. Keep your head secure and ride with confidence on the slopes.', img: 'https://i.imgur.com/EnvkUqr.png' },
    { name: 'Sandbox Classic 2.0 Snow Helment', brand: 'Burton',  cat: 'Helmet', price: 119.96, description: 'Guard your head with the Sandbox Classic 2.0 Snow Helmet. An essential companion for snowboarding enthusiasts, this helmet features advanced protection technology and a comfortable fit. Keep your head secure and hit the slopes in style.', img: 'https://i.imgur.com/XFg6wj5.png' },
    { name: 'Burton Brain Bucket', brand: 'Burton', cat: 'Helmet', price: 325, description: 'Keep your head safe with the Burton Brain Bucket Helmet. This reliable helmet is a must-have for every snowboarding enthusiast, featuring advanced protection technology and a comfortable fit. Ensure your head stays secure as you conquer the slopes.', img: 'https://i.imgur.com/sbSHOPu.png' },
  ]);
  


  process.exit();
})();
